### ISSUE TITLE
Allowing strings in row 2

### ISSUE THREAD

**Issue by rpakr-googology** [koteitan/hydraviewer#7]
Currently only numbers are allowed in the second row (i.e. inside nodes of hydras). However, I think allowing strings of ASCII characters (probably excluding ")") in the second row (if not possible, alphabets) will make it easier for people to explain using hydra images, since they will be able to use alphabets to indicate subhydras. It will also help if the circles can become ellipses when the string inside them is long and does not fit in the circle.

**Comment by koteitan** [comment]
Nice idea. I'll try it!

**Comment by koteitan** [comment]
Done in version 1.6. 

Here you are: http://www.ukaibutton.com/hydraviewer/ 

If you doesn't have the effect, please try removing of the cache (just Ctrl+Shift+R by chrome)
